spring:
  application:
    name: hotel-admin-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: postgres
    password: postgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
server:
  port: 8080


